"""DepthRouter research primitives."""

from .causal_memory import (
    PageLayout,
    coalesced_transfer_bytes,
    greedy_affinity_layout,
    page_masses,
    posterior_affinity,
    posterior_entropy,
    predictive_working_set_bytes,
    random_layout,
    requested_pages,
    sequential_layout,
    smooth_address_entropy_nats,
    working_set_pages,
)
from .config import DepthRouterConfig
from .conformal_memory import (
    anytime_bonferroni_thresholds,
    aps_calibration_threshold,
    aps_prediction_mask,
    bytes_for_mask,
    empirical_coverage,
    mean_set_size,
    nested_anytime_masks,
    required_set_calibration_threshold,
    required_set_coverage,
)
from .model import DepthRouterModel, ForwardStats, StackedTransformerBaseline
from .solver import (
    KLFaultPolicy,
    Move,
    SolverState,
    SwitchableColdMLP,
    coalesce_faults,
    kl_nats,
    unique_fault_bytes,
    value_per_byte,
)

__all__ = [
    "DepthRouterConfig",
    "DepthRouterModel",
    "ForwardStats",
    "KLFaultPolicy",
    "Move",
    "PageLayout",
    "SolverState",
    "StackedTransformerBaseline",
    "SwitchableColdMLP",
    "anytime_bonferroni_thresholds",
    "aps_calibration_threshold",
    "aps_prediction_mask",
    "bytes_for_mask",
    "coalesce_faults",
    "coalesced_transfer_bytes",
    "empirical_coverage",
    "greedy_affinity_layout",
    "kl_nats",
    "mean_set_size",
    "nested_anytime_masks",
    "page_masses",
    "posterior_affinity",
    "posterior_entropy",
    "predictive_working_set_bytes",
    "random_layout",
    "requested_pages",
    "required_set_calibration_threshold",
    "required_set_coverage",
    "sequential_layout",
    "smooth_address_entropy_nats",
    "unique_fault_bytes",
    "value_per_byte",
    "working_set_pages",
]
